from enum import StrEnum


class EvidenceState(StrEnum):
    SUFFICIENT = "SUFFICIENT"
    PARTIAL = "PARTIAL"
    CONFLICTING = "CONFLICTING"
    NO_EVIDENCE = "NO_EVIDENCE"
    PATIENT_DATA_MISSING = "PATIENT_DATA_MISSING"
    LOW_CONFIDENCE_INPUT = "LOW_CONFIDENCE_INPUT"
    HIGH_RISK = "HIGH_RISK"


class AgentAction(StrEnum):
    ANSWER = "ANSWER"
    ASK = "ASK"
    CREATE_REMINDER = "CREATE_REMINDER"
    RECOMMEND_ROUTINE_VISIT = "RECOMMEND_ROUTINE_VISIT"
    ESCALATE_URGENT = "ESCALATE_URGENT"
    REFUSE = "REFUSE"
